CREATE TABLE FORM(
    id serial primary key,
    mission_id int references Missiondata(id),
    nachbarschaftshilfe int not null,
    kategorie varchar(20) not null,
    GerettetAusGebäude default(0),
    gerettetAusKFZ default(0),
    verletzteZivilpersonen default(0),
    totgeborgeneZivilpersonen default(0),
    geretteteTiere default(0),
    totgeborgeneTiere default(0),
    Entdeckung varchar(20),
    Ausmaß varchar(20),
    Klasse varchar(20),
    Brand varchar(20),
    Objektart varchar(20),
    Bauart varchar(20),
    Lage varchar(20),
    Verlauf varchar(20),
    Ursache varchar(20),
    Haupttätigkeit varchar(20),
    Stoffe varchar(20),
    AndereTätigkeiten varchar(20)
);